apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ack-cloudwatch-controller.app.fullname" . }}-namespace-caches
  labels:
    app.kubernetes.io/name: {{ include "ack-cloudwatch-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-cloudwatch-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-cloudwatch-controller.chart.name-version" . }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "ack-cloudwatch-controller.app.fullname" . }}-namespace-caches
subjects:
- kind: ServiceAccount
  name: {{ include "ack-cloudwatch-controller.service-account.name" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ack-cloudwatch-controller.app.fullname" . }}-configmaps-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-cloudwatch-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-cloudwatch-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-cloudwatch-controller.chart.name-version" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "ack-cloudwatch-controller.app.fullname" . }}-configmaps-cache
subjects:
- kind: ServiceAccount
  name: {{ include "ack-cloudwatch-controller.service-account.name" . }}
  namespace: {{ .Release.Namespace }}
