{{ $labels := .Values.role.labels }}
{{ $appVersion := .Chart.AppVersion | quote }}
{{ $rbacRules := include "ack-cloudwatch-controller.rbac-rules" . }}
{{ $fullname := include "ack-cloudwatch-controller.app.fullname" . }}
{{ $chartVersion := include "ack-cloudwatch-controller.chart.name-version" . }}
{{ if eq .Values.installScope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ack-cloudwatch-controller.app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ack-cloudwatch-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-cloudwatch-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-cloudwatch-controller.chart.name-version" . }}
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{$rbacRules }}
{{ else if eq .Values.installScope "namespace" }}
{{ $wn := include "ack-cloudwatch-controller.watch-namespace" . }}
{{ $namespaces := split "," $wn }}
{{ range $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}-{{ . }}
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ $appVersion }}
    k8s-app: {{ $fullname }}
    helm.sh/chart: {{ $chartVersion }}
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ $rbacRules }}
{{ end }}
{{ end }}