apiVersion: v1
name: cloudwatch-chart
description: A Helm chart for the ACK service controller for Amazon CloudWatch (CloudWatch)
version: 0.0.2
appVersion: 0.0.2
home: https://github.com/aws-controllers-k8s/cloudwatch-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/cloudwatch-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: CloudWatch Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/cloudwatch-maintainer
keywords:
  - aws
  - kubernetes
  - cloudwatch
